# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: ruuftop.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: TCA
    Domain: tca.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: BATA
    Domain: bata.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: SANDAG
    Domain: sandag.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: REPORT
    Domain: report.com
    Template:
      Count: 1
    Users:
      Count: 1
